name: ScoreboardReset
version: 2.0
main: fr.archimonde.scoreboardreset.ScoreboardReset
api-version: 1.19
author: Archimonde
description: Bloque les packets scoreboard de TAB/BungeeCord pour laisser TheLab gérer son propre scoreboard
depend:
  - ProtocolLib
 
